export const data = {
  title: "Terms and Conditions",
  desc: "Welcome to our website. If you continue to browse and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our ‘Privacy Policy’, govern readywealth.in (A brand of Fortune Alfa Services Pvt Ltd) relationship with you. The term “FAS” (Fortune Alfa Services Pvt Ltd) refers to the owner of the website. The term “you” refers to the user or viewer of our website.",
  subH1: "The use of this website is subject to the following terms:",
  subP1: [
    `You understand and accept that FAS maintains the website – http://www.readywealth.in to provide visitors with information about FAS its services and products, and to enable visitors to avail its services. You also accept that visitors to the site are required to read the below terms, and the use of the site constitutes your acceptance and agreement to be bound by such terms. You will also be bound by changes therein to the terms from time-to-time as communicated and made available on the website.`,
    `You understand and accept that all information submitted by you on the site shall be deemed the property of FAS, and FAS shall be free to use any ideas, concepts, know-how or techniques provided by you in any manner whatsoever. On initiating contact through the site, you agree to being contacted by FAS, or any other entities with whom FAS has entered into an arrangement, via email, phone call, SMS or any other means. You agree that you shall not copy, reproduce, sell, redistribute, publish, enter into a database, display, perform, modify, transmit, license, create derivatives from, transfer, or in any way exploit, any part of any information, content, materials, services available on or through the site, except that which you may download for your own personal, non-commercial use.`,
    `You agree that you will not use FAS’s website for any purpose that is unlawful, or prohibited by these terms. You also agree you will not use the site in any manner that could damage, disable or impair the website, or interfere with any other party’s use, or enjoyment of the website.`,
    `You acknowledge that the software and hardware underlying the site, as well as other Internet-related software required for accessing the website, are the legal property of the respective vendors. The permission given by FAS to access the website will not convey any proprietary or ownership rights in the above software/hardware. You agree that you shall not attempt to modify, translate, disassemble, decompile, or reverse engineer the software/ hardware underlying the website, or create any derivative product based on the software/hardware.`,
    `You understand and accept that not all products and services offered on this website are available in all geographic areas, and you may not be eligible for all the products or services offered by FAS on the site. FAS reserves the right to determine the availability and eligibility for any product or service.`,
    `You understand and accept that FAS is not responsible for the availability of content, or other services on third-party sites linked from the website. You are aware that the access of hyperlinks to other internet sites are at your own risk, and the content, accuracy, opinions expressed, and other links provided by these sites are not verified, monitored or endorsed by FAS in any way. FAS does not make any warranties, and expressly disclaims all warranties, express or implied, including without limitation, those of merchantability and fitness for a particular purpose, title or non-infringement with respect to any information or services or products that are available or advertised or sold through these third-party websites.`,
    `FAS shall not be liable if any transaction does not fructify, or may not be completed, or for any failure on the part of FAS to perform any of its obligations under these terms and conditions, or those applicable specifically to its services/facilities if performance is prevented, hindered or delayed by a Force Majeure event (defined below). In such a case, its obligations shall be suspended for so long as the Force Majeure event continues.`,
    `“Force Majeure Event” means any event due to any cause beyond the reasonable control of FAS, including and without limitations the unavailability of any communication systems, breach, or virus in the processes or payment or delivery mechanism, sabotage, fire, flood, explosion, acts of God, civil commotions, strikes or industrial action of any kind, riots, insurrection, war, acts of the government, computer hacking, unauthorised access to computer data and storage devices, computer crashes, malfunctioning in the computer terminal, or the systems getting affected by any malicious, destructive or corrupting code or programme, mechanical or technical errors/failures or power shutdown, faults or failures in telecommunication, etc.`,
    `You understand and accept that FAS has the absolute discretion to amend or supplement any of the terms at any time, and will give a prior notice of 30 days for such changes. The changed terms and conditions shall be communicated to you on the website, and by other acceptable modes of communication. By using FAS’s services, you shall be deemed to have accepted the changed terms and conditions.`,
    `You accept that the Courts in Pune alone shall have exclusive jurisdiction as regards to any claims or matters arising out of dealings with FAS. All disputes will be governed by the laws of India.`,
    `You understand and agree that these terms are in addition to, and not in derogation of, the applicable terms and conditions relating to your usage of any FAS services that you may be currently availing, or may avail in the future.`,
  ],
};
